### ISSUE TITLE
Can not load the PushySDK.framework/PushySDK

### ISSUE THREAD

**Issue by vielucasluu** [pushy-me/pushy-demo-ios#1]
dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib
  Referenced from: /Users/lucasluu/Library/Developer/CoreSimulator/Devices/EF79A0C1-391D-460B-8FBC-CF08B2D377F9/data/Containers/Bundle/Application/093725E4-9217-4F90-9172-1BC3DA2F411E/HaNoi.app/Frameworks/PushySDK.framework/PushySDK
  Reason: image not found

**Comment by pushy** [comment]
Hi @LadyRanger1992,
Thank you for your report.

Which version of Xcode are you using? Also, is your iOS project a Swift one?

**Comment by vielucasluu** [comment]
I using CocoaPods in Objective-C Project.
With XCode 7.3.1

**Comment by pushy** [comment]
You will need to update to Xcode 8 or newer to use our SDK.

**Comment by vielucasluu** [comment]
Many libs using in our project run in Swift 2.2 or Swift 2.3
We can not upgrade to XCode 8.

**Comment by pushy** [comment]
Unfortunately, at this time we are unable to support Swift 2.3 due to the substantial syntax/class differences between Swift 2.3 and 3.0.

Please check whether your referenced libraries have been updated to Swift 3.0 -- if they are popular, chances are they have been updated since Swift 3.0 was released on September 13th, over 3 months ago.
